site_name: æternity Documentation Hub
nav:
    - Introduction: 'index.md'
    - Node:
        - Introduction: 'æternity/README.md'
        - Get Started:
            - Build in Windows: 'æternity/docs/build-windows.md'
            - Build in Ubuntu: 'æternity/docs/build.md'
            - Configuration: 'æternity/docs/configuration.md'
            - CUDA Miner: 'æternity/docs/cuda-miner.md'
            - Docker: 'æternity/docs/docker.md'
            - Installation in Windows: 'æternity/docs/installation-windows.md'
            - Installation in Ubuntu: 'æternity/docs/installation.md'
            - Operation: 'æternity/docs/operation.md'
    - Protocol:
        - Oracles:
            - Life Cycle: 'protocol/oracles/oracle_life_cycle.md'
            - State Tree: 'protocol/oracles/oracle_state_tree.md'
            - Transactions: 'protocol/oracles/oracle_transactions'
        - AENS Naming System: 'protocol/AENS.md'
        - Smart Contracts:
            - Contract Life Cycle Examples: 'protocol/contracts/contract_life_cycle.md'
            - Virtual Machines:
                - Æternity VM: 'protocol/contracts/contract_vms.md'
                - Æternity Ethereum VM: 'protocol/contracts/aevm.md'
            - Sophia Smart Contract Language: 'protocol/contracts/sophia.md'
            - Contract State Tree: 'protocol/contracts/contract_state_tree.md'
            - Contract Transactions: 'protocol/contracts/contract_transactions.md'
        - State Channels: 'protocol/channels/README.md'
        - Serialization Formats: 'protocol/serializations.md'
    - Expansions:
        - AEX's:
            - AEX1: 'Expansions/AEXS/aex-1.md'
            - AEX2: 'Expansions/AEXS/aex-2.md'
    # - Developer Tools:
    #     - SDK's:
    #         - Go
    #         - JavaScript
    #         - Python
    #     - CLI Tools:
    #         - JavaScript
    #         - Stratum:
    #            - Library
    #         - Websocket
    #     - Middleware:
    #     - Frameworks:
    #         - ForgAE
    #         - æpp Components
    #     - Online Test Tools:
    #         - Smart Contract Editor
    #         - Blockchain Explorer
    #         - Faucet
    #            - Token Faucet
    #            - æpp Faucet
    # - Sophia Library:
    # - Sophia by Example:
    # - Tutorial:
    #     - Development:
    #     - Mining:
extra_css: [site/assets/extra.css]
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

repo_name: 'aeternity/documentation-hub'
repo_url: 'https://github.com/aeternity/documentation-hub'
